# Generated by Django 5.1.5 on 2025-01-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sporty', '0001_initial'),
        ('teamy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('status', models.CharField(choices=[('nadchazejici', 'Nadcházející'), ('probihajici', 'Probíhající'), ('ukoncene', 'Ukončené')], max_length=20)),
                ('domaci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domaci_zapasy', to='teamy.team')),
                ('hoste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoste_zapasy', to='teamy.team')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.sport')),
            ],
        ),
    ]
