# Generated by Django 5.1.5 on 2025-02-25 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
        ('zapasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zapas',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zapas',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='datum',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='status',
            field=models.CharField(choices=[('nadchazejici', 'Nadcházející'), ('probihajici', 'Probíhající'), ('paused', 'Pozastaveno'), ('ukoncene', 'Ukončené')], max_length=20),
        ),
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.sport')),
                ('zapasy', models.ManyToManyField(to='zapasy.zapas')),
            ],
        ),
    ]
