# Generated by Django 5.1.6 on 2025-02-24 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sporty', '0001_initial'),
        ('zapasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=20)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sporty.sport')),
                ('zapasy', models.ManyToManyField(to='zapasy.zapas')),
            ],
        ),
    ]
