# Generated by Django 5.1.6 on 2025-02-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasy', '0003_alter_zapas_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapas',
            name='elapsed_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zapas',
            name='pause_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='zapas',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zapas',
            name='status',
            field=models.CharField(choices=[('nadchazejici', 'Nadcházející'), ('probihajici', 'Probíhající'), ('paused', 'Pozastaveno'), ('ukoncene', 'Ukončené')], max_length=20),
        ),
    ]
