# Generated by Django 5.1.6 on 2025-03-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zapasy', '0004_zapas_elapsed_time_zapas_pause_time_zapas_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapas',
            name='status',
            field=models.CharField(choices=[('nadchazejici', 'Nadcházející'), ('probihajici', 'Probíhající'), ('paused', 'Pozastaveno'), ('ukoncene', 'Ukončené')], default='nadchazejici', max_length=20),
        ),
    ]
