# Generated by Django 5.1.5 on 2025-03-20 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamy', '0004_alter_hrac_cislo'),
        ('zapasy', '0005_alter_zapas_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabulkaBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.IntegerField(default=0)),
                ('liga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zapasy.liga')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamy.team')),
            ],
            options={
                'unique_together': {('team', 'liga')},
            },
        ),
    ]

