# Generated by Django 5.1.5 on 2025-01-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrac',
            name='team',
        ),
        migrations.AlterField(
            model_name='team',
            name='hraci',
            field=models.ManyToManyField(related_name='team', to='teamy.hrac'),
        ),
    ]
