# Generated by Django 5.1.6 on 2025-02-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamy', '0003_alter_hrac_cislo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrac',
            name='cislo',
            field=models.IntegerField(),
        ),
    ]
