# Generated by Django 5.1.6 on 2025-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='disqualified',
            field=models.BooleanField(default=False),
        ),
    ]
