# Generated by Django 5.1.5 on 2025-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(choices=[('fotbal', 'Fotbal'), ('hazena', 'Házená'), ('hokej', 'Hokej')], max_length=20, unique=True)),
            ],
        ),
    ]
