# Generated by Django 5.1.5 on 2025-01-26 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zapasy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casomira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(null=True)),
                ('konec', models.DateTimeField(null=True)),
                ('segment', models.IntegerField(default=1)),
                ('zapas', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zapasy.zapas')),
            ],
        ),
    ]
